### ISSUE TITLE
Twitch library error while trying to launch a old package.

### ISSUE THREAD

**Issue by sylphio** [hedgehog1029/Launcher#2]
First, thank for your great work .

it work really well with new forge build .

When, i try to run a old 1.7.10 package, it nearly work with the exception of two libraries errors.. 

[avertissement] Failed to download https://libraries.minecraft.net/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-${arch}.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-${arch}.jar
[avertissement] Failed to download https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-${arch}.jar
java.io.IOException: Did not get expected response code, got 404 for https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-${arch}.jar

It look like the ${arch} should be expanded to 32 or 64 by the launcher.

**Comment by hedgehog1029** [comment]
ah! that's fun, twitch only has natives for windows but i'm on linux so I didn't hit this bug. should be a simple fix but #3 is not quite right, i'll throw in a fix myself
