### ISSUE TITLE
Fancy launcher  no longer compile with Jdk 1.8 

### ISSUE THREAD

**Issue by sylphio** [hedgehog1029/Launcher#5]
You probably already know but since the last batch of commit. The fancy launcher no longer compile with jdk 1.8.

**Comment by hedgehog1029** [comment]
hmm, I had a commit which broke java 8, but then I thought I fixed it.

**Comment by hedgehog1029** [comment]
if you have a stack trace or other error can you drop it here? I will be asleep for a while but I'll take a look tomorrow

**Comment by hedgehog1029** [comment]
I can't seem to reproduce this (and a friend of mine couldn't either); both compiling and running with java 8 seems to work fine for me.
