### ISSUE TITLE
[Creator Tools] Error when attempting to delete non-existent instances directory

### ISSUE THREAD

**Issue by ChloeDawn** [hedgehog1029/Launcher#7]
**Version:** 2.0.2-SNAPSHOT

I feel like this should just be a no-op state, rather than producing an error.

![Screenshot of error dialog](https://i.imgur.com/XbXTgtw.png)

**Comment by hedgehog1029** [comment]
I think having the error is fine, and it has a clear enough message... maybe I will remove the stacktrace if possible, to avoid confusion.
